FROM docker.1ms.run/library/ubuntu:22.04

# x86
RUN sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
RUN sed -i 's/security.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
# arm
#RUN sed -i 's/ports.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list

RUN apt-get update && \
    apt-get install -y git curl jq wget build-essential net-tools vim unzip \
    python3-dev python3-pip python3-venv \
    libprotobuf-dev protobuf-compiler libssl-dev pkg-config

RUN echo -e "set number\nset paste\nset expandtab\nset tabstop=4\n" > ~/.vimrc

RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
RUN pip config set install.trusted-host mirrors.aliyun.com

# python3 link
RUN ln -s /usr/bin/python3 /usr/bin/python

RUN mkdir -p /opt/venv && \
    python3 -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install --upgrade pip build wheel maturin patchelf

ENV VIRTUAL_ENV=/opt/venv
ENV PATH="${VIRTUAL_ENV}/bin:${PATH}"

# 工作目录
WORKDIR /workspace

ENV RUSTUP_DIST_SERVER=https://mirrors.aliyun.com/rustup
ENV RUSTUP_UPDATE_ROOT=https://mirrors.aliyun.com/rustup/rustup

RUN curl --proto '=https' --tlsv1.2 -sSf https://mirrors.aliyun.com/repo/rust/rustup-init.sh -o rustup-init.sh \
    && chmod +x rustup-init.sh \
    && sh rustup-init.sh -y \
    && rm rustup-init.sh

RUN mkdir -vp $HOME/.cargo \
    && touch $HOME/.cargo/config.toml \
    && echo '[source.crates-io]' > $HOME/.cargo/config.toml \
    && echo "replace-with = 'aliyun'"  >> $HOME/.cargo/config.toml \
    && echo '[source.aliyun]'   >> $HOME/.cargo/config.toml \
    && echo 'registry = "sparse+https://mirrors.aliyun.com/crates.io-index/"'  >> $HOME/.cargo/config.toml

RUN echo '. "$HOME/.cargo/env"' >> ~/.bashrc
