FROM quay.mirrorify.net/openeuler/openeuler:24.03

# Ensure apt-get won't prompt for selecting options
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

RUN sed -i 's|repo.openeuler.org|mirrors.aliyun.com/openeuler|g' /etc/yum.repos.d/openEuler.repo
RUN sed -i '/^metalink=/ s/^/#/' /etc/yum.repos.d/openEuler.repo
# openeuler 关闭update标识
RUN sed -i '/^\[update\]$/,/^\[.*\]$/ s/^enabled=1$/enabled=0/' /etc/yum.repos.d/openEuler.repo
RUN sed -i '/^\[update-source\]$/,/^\[.*\]$/ s/^enabled=1$/enabled=0/' /etc/yum.repos.d/openEuler.repo

# build/dev dependencies
RUN dnf makecache && \
    dnf install -yq python3-devel python3-pip protobuf-devel protobuf-compiler openssl-devel net-tools pkgconfig

RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/
RUN pip config set install.trusted-host mirrors.aliyun.com

RUN mkdir -p /opt/venv && \
    python3 -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install --upgrade pip build wheel maturin patchelf pre-commit ruff

ENV VIRTUAL_ENV=/opt/venv
ENV PATH="${VIRTUAL_ENV}/bin:${PATH}"

# 工作目录
WORKDIR /workspace

ENV RUSTUP_DIST_SERVER=https://mirrors.aliyun.com/rustup
ENV RUSTUP_UPDATE_ROOT=https://mirrors.aliyun.com/rustup/rustup

RUN curl --proto '=https' --tlsv1.2 -sSf https://mirrors.aliyun.com/repo/rust/rustup-init.sh -o rustup-init.sh \
    && chmod +x rustup-init.sh \
    && sh rustup-init.sh -y \
    && rm rustup-init.sh

RUN mkdir -vp $HOME/.cargo \
    && touch $HOME/.cargo/config.toml \
    && echo '[source.crates-io]' > $HOME/.cargo/config.toml \
    && echo "replace-with = 'aliyun'"  >> $HOME/.cargo/config.toml \
    && echo '[source.aliyun]'   >> $HOME/.cargo/config.toml \
    && echo 'registry = "sparse+https://mirrors.aliyun.com/crates.io-index/"'  >> $HOME/.cargo/config.toml

RUN echo '. "$HOME/.cargo/env"' >> ~/.bashrc
